### ISSUE TITLE
Limit the amount of Special Attacks and Heals

### ISSUE THREAD

**Issue by karlm89** [karlm89/humans-vs-ai#2]
Keep people from spamming special attacks, and heals!

**Comment by NobilityGaming** [comment]
Made pull request with this problem solved.

**Comment by karlm89** [comment]
Thanks you so much!

**Comment by karlm89** [comment]
@NobilityGaming -- Perhaps setting a limit on how many times they can use either feature. ie : Special Attack : 3 times Heal: 2 times.
